# These are supported funding model platforms

github: [your-github-username] # Replace with actual username
patreon: # Add if setting up Patreon
open_collective: # Add if setting up Open Collective
ko_fi: # Add if setting up Ko-fi
tidelift: # Add if using Tidelift
community_bridge: # Add if using Community Bridge
issuehunt: # Add if using IssueHunt
otechie: # Add if using Otechie
liberapay: # Add if using Liberapay
custom: # Add custom donation links
